function marsRegions = marsLabels2Regions(marsLabels)
    marsLabelsAll = {'VCcm', 'VCl', 'VCs', 'Cu', 'VCrm', 'ITCm', 'ITCr', 'MTCc', 'STCc', ...,
        'STCr', 'MTCr', 'IPCv', 'IPCd', 'SPC', 'SPCm', 'PCm', 'Sv', 'Sdl', 'Sdm', ...
        'ICC', 'PCC', 'MCC', 'ACC', 'Mv', 'Mdl', 'Mdm', 'PMrv', 'PMdl', 'PMdm', ...
        'PFcdl', 'PFcdm', 'PFrvl', 'Pfrdli', 'Pfrdls', 'PFrd', 'PFrm', 'OFCvl', ...
        'OFCv', 'OFCvm', 'PFCvm', 'Insula', 'Thalamus', 'Caudate', 'Puttamen', ...
        'Pallidum', 'Hippocampus', 'Amygdala', 'Accumbens'};
    marsRegionsAll = {'Occipital', 'Occipital', 'Occipital', 'Occipital', ...
        'Occipital', 'Temporal', 'Temporal', 'Temporal', 'Temporal', 'Temporal', ... 
        'Temporal', 'Parietal', 'Parietal', 'Parietal', 'Parietal', 'Parietal', ... 
        'Parietal', 'Parietal', 'Parietal', 'Cingular', 'Cingular', 'Cingular', ...
        'Cingular', 'Frontal', 'Frontal', 'Frontal', 'Frontal', 'Frontal', 'Frontal', ...
        'Frontal', 'Frontal', 'Frontal', 'Frontal', 'Frontal', 'Frontal', 'Frontal', ... 
        'Orbito-Frontal', 'Orbito-Frontal', 'Orbito-Frontal', 'Orbito-Frontal', ... 
        'Insula', 'Subcortical', 'Subcortical', 'Subcortical', 'Subcortical', ... 
        'Subcortical', 'Subcortical', 'Subcortical'};
    % convert labels to lobes
    marsRegions = cell(size(marsLabels));
    for l=1:length(marsLabels)
        parts = split(marsLabels{l}, '-');
        lat = parts{1};
        label = parts{2};
        region = marsRegionsAll{strcmp(marsLabelsAll, label)};
        marsRegions{l} = strcat(lat, '-', region);
    end

end